name: Pipeline Inicial

on:
  push:
    branches:
      - main

jobs:
  Docker-Action:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Compose Up
        run: docker compose up -d